services:
  jupyter:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
      - jupyter_data:/app
      - jupyter_deps:/usr/local/lib/python3.8/site-packages
    ports:
      - "8888:8888"
    environment:
      - NAME=World
    command: ["jupyter", "notebook", "--ip=0.0.0.0", "--port=8888", "--no-browser", "--allow-root"]

volumes:
  jupyter_data:
    driver: local
  jupyter_deps:
    driver: local
